"""initial

Revision ID: 108a74f3d3b9
Revises: 
Create Date: 2026-02-24 21:27:42.447725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108a74f3d3b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('middle_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('organizations',
    sa.Column('organization_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('time_gap', sa.Integer(), nullable=True, comment='интервал / gap в минутах (например: 60 = 1 час)'),
    sa.Column('granular_step', sa.SmallInteger(), nullable=True, comment='шаг сетки расписания в минутах'),
    sa.Column('is_enable', sa.Boolean(), nullable=False, comment='организация активна'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_index(op.f('ix_organizations_admin_id'), 'organizations', ['admin_id'], unique=False)
    op.create_index(op.f('ix_organizations_is_enable'), 'organizations', ['is_enable'], unique=False)
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_clients_account_id'), 'clients', ['account_id'], unique=False)
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_table('managers',
    sa.Column('managers_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('managers_id')
    )
    op.create_index(op.f('ix_managers_account_id'), 'managers', ['account_id'], unique=False)
    op.create_index(op.f('ix_managers_organization_id'), 'managers', ['organization_id'], unique=False)
    op.create_table('masters',
    sa.Column('master_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('master_id')
    )
    op.create_index(op.f('ix_masters_account_id'), 'masters', ['account_id'], unique=False)
    op.create_index(op.f('ix_masters_organization_id'), 'masters', ['organization_id'], unique=False)
    op.create_table('organization_archive',
    sa.Column('organization_archive_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('revenue', sa.Numeric(), nullable=True),
    sa.Column('booking_count', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('work_period', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('organization_archive_id')
    )
    op.create_index(op.f('ix_organization_archive_organization_id'), 'organization_archive', ['organization_id'], unique=False)
    op.create_table('services',
    sa.Column('service_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('service_group', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('service_pk')
    )
    op.create_index(op.f('ix_services_organization_id'), 'services', ['organization_id'], unique=False)
    op.create_table('templates',
    sa.Column('template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('week_day', sa.SmallInteger(), nullable=True),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_templates_organization_id'), 'templates', ['organization_id'], unique=False)
    op.create_table('masters_archive',
    sa.Column('master_archive_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('released_hours', sa.Numeric(), nullable=True),
    sa.Column('released_amount', sa.Numeric(), nullable=True),
    sa.Column('cheats_hours', sa.Numeric(), nullable=True),
    sa.Column('booking_count', sa.Integer(), nullable=True),
    sa.Column('work_day', sa.Date(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.master_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('master_archive_id')
    )
    op.create_index(op.f('ix_masters_archive_master_id'), 'masters_archive', ['master_id'], unique=False)
    op.create_index(op.f('ix_masters_archive_organization_id'), 'masters_archive', ['organization_id'], unique=False)
    op.create_table('schedulers',
    sa.Column('scheduler_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.master_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.template_id'], ),
    sa.PrimaryKeyConstraint('scheduler_id')
    )
    op.create_index(op.f('ix_schedulers_master_id'), 'schedulers', ['master_id'], unique=False)
    op.create_index(op.f('ix_schedulers_template_id'), 'schedulers', ['template_id'], unique=False)
    op.create_table('service_masters',
    sa.Column('service_master_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('price_grp', sa.Integer(), nullable=True),
    sa.Column('day_start', sa.Date(), nullable=True),
    sa.Column('day_finish', sa.Date(), nullable=True),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.master_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_pk'], ),
    sa.PrimaryKeyConstraint('service_master_id')
    )
    op.create_index(op.f('ix_service_masters_master_id'), 'service_masters', ['master_id'], unique=False)
    op.create_index(op.f('ix_service_masters_organization_id'), 'service_masters', ['organization_id'], unique=False)
    op.create_index(op.f('ix_service_masters_service_id'), 'service_masters', ['service_id'], unique=False)
    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('booking_dt', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['masters.master_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_masters.service_master_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index('ix_booking_client', 'booking', ['client_id'], unique=False)
    op.create_index(op.f('ix_booking_client_id'), 'booking', ['client_id'], unique=False)
    op.create_index('ix_booking_master_dt', 'booking', ['booking_dt', 'master_id'], unique=False)
    op.create_index(op.f('ix_booking_master_id'), 'booking', ['master_id'], unique=False)
    op.create_index('ix_booking_organization', 'booking', ['organization_id'], unique=False)
    op.create_index(op.f('ix_booking_organization_id'), 'booking', ['organization_id'], unique=False)
    op.create_index(op.f('ix_booking_service_id'), 'booking', ['service_id'], unique=False)
    op.create_table('client_archive',
    sa.Column('client_archive_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_master_id', sa.Integer(), nullable=False),
    sa.Column('visit_start_dt', sa.DateTime(), nullable=True),
    sa.Column('visit_end_dt', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['service_master_id'], ['service_masters.service_master_id'], ),
    sa.PrimaryKeyConstraint('client_archive_id')
    )
    op.create_index(op.f('ix_client_archive_client_id'), 'client_archive', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_archive_organization_id'), 'client_archive', ['organization_id'], unique=False)
    op.create_index(op.f('ix_client_archive_service_master_id'), 'client_archive', ['service_master_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=True)
    op.create_index(op.f('ix_reviews_organization_id'), 'reviews', ['organization_id'], unique=False)
    # ### end Alembic commands ###
    op.alter_column('booking', 'service_id', nullable=True)
    op.alter_column('booking', 'client_id', nullable=True)
    op.execute("""
               CREATE OR REPLACE PROCEDURE generate_5min_slots_for_master(
                    p_master_id       INT,
                    p_start_date      DATE,           -- с какого дня начинать
                    p_end_date        DATE DEFAULT NULL,  -- по какой день (если NULL → только p_start_date)
                    p_organization_id INT DEFAULT NULL    -- если известен, можно передать для ускорения
                )
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    v_org_id          INT;
                    v_step            INTERVAL := '5 minutes';
                    v_slot_time       TIME;
                    v_slot_dt         TIMESTAMP;
                    v_day             DATE;
                    v_time_from       TIME;
                    v_time_to         TIME;
                    v_rec             RECORD;
                BEGIN
                    -- Определяем organization_id, если не передан
                    IF p_organization_id IS NULL THEN
                        SELECT organization_id
                        INTO v_org_id
                        FROM masters
                        WHERE master_id = p_master_id;
                
                        IF NOT FOUND THEN
                            RAISE EXCEPTION 'Мастер с id % не найден', p_master_id;
                        END IF;
                    ELSE
                        v_org_id := p_organization_id;
                    END IF;
                
                    -- Проверяем, что диапазон дат корректный
                    IF p_end_date IS NULL THEN
                        p_end_date := p_start_date;
                    END IF;
                
                    IF p_start_date > p_end_date THEN
                        RAISE EXCEPTION 'Дата начала позже даты окончания';
                    END IF;
                
                    -- Проходим по каждому дню
                    FOR v_day IN
                        SELECT d::date
                        FROM generate_series(p_start_date, p_end_date, '1 day'::interval) d
                    LOOP
                        -- Находим шаблон(ы) для этого мастера и дня недели
                        FOR v_rec IN
                            SELECT t.time_from, t.time_to
                            FROM schedulers     s
                            JOIN templates      t ON t.template_id = s.template_id
                            WHERE s.master_id = p_master_id
                              AND t.week_day  = EXTRACT(DOW FROM v_day)::smallint
                              AND t.organization_id = v_org_id
                            ORDER BY t.time_from
                        LOOP
                            -- Генерируем слоты с шагом 5 минут
                            v_slot_time := v_rec.time_from;
                
                            WHILE v_slot_time < v_rec.time_to LOOP
                                v_slot_dt := v_day + v_slot_time;
                
                                -- Проверяем, нет ли уже записи на это время у этого мастера
                                -- (благодаря уникальному индексу idx_booking_master вставка упадёт, но мы проверяем заранее)
                                IF NOT EXISTS (
                                    SELECT 1
                                    FROM booking
                                    WHERE master_id = p_master_id
                                      AND booking_dt = v_slot_dt
                                ) THEN
                                    INSERT INTO booking (
                                        client_id,
                                        service_id,
                                        master_id,
                                        booking_dt,
                                        status,
                                        organization_id
                                    )
                                    VALUES (
                                        NULL,
                                        p_service_id,
                                        p_master_id,
                                        v_slot_dt,
                                        'free',
                                        v_org_id
                                    )
                                    ON CONFLICT (booking_dt, master_id) DO NOTHING;
                                END IF;
                
                                v_slot_time := v_slot_time + v_step;
                            END LOOP;
                
                        END LOOP;  -- конец цикла по шаблонам дня
                
                    END LOOP;  -- конец цикла по дням
                
                    RAISE NOTICE 'Слоты 5 минут для мастера % с % по % сгенерированы', 
                                 p_master_id, p_start_date, p_end_date;
                
                EXCEPTION
                    WHEN others THEN
                        RAISE EXCEPTION 'Ошибка при генерации слотов для мастера %: %', 
                                        p_master_id, SQLERRM;
                END;
                $$;
               """)
    op.create_unique_constraint(
        'uq_booking_dt_master',
        'booking',
        ['booking_dt', 'master_id']
    )
    op.create_index(
        'ux_master_archive_unique',
        'masters_archive',
        ['master_id', 'work_day', 'organization_id'],
        unique=True
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_organization_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_index(op.f('ux_master_archive_unique'), table_name='masters_archive')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_client_archive_service_master_id'), table_name='client_archive')
    op.drop_index(op.f('ix_client_archive_organization_id'), table_name='client_archive')
    op.drop_index(op.f('ix_client_archive_client_id'), table_name='client_archive')
    op.drop_table('client_archive')
    op.drop_index(op.f('ix_booking_service_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_organization_id'), table_name='booking')
    op.drop_index('ix_booking_organization', table_name='booking')
    op.drop_index(op.f('ix_booking_master_id'), table_name='booking')
    op.drop_index('ix_booking_master_dt', table_name='booking')
    op.drop_index(op.f('ix_booking_client_id'), table_name='booking')
    op.drop_index('ix_booking_client', table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_service_masters_service_id'), table_name='service_masters')
    op.drop_index(op.f('ix_service_masters_organization_id'), table_name='service_masters')
    op.drop_index(op.f('ix_service_masters_master_id'), table_name='service_masters')
    op.drop_table('service_masters')
    op.drop_index(op.f('ix_schedulers_template_id'), table_name='schedulers')
    op.drop_index(op.f('ix_schedulers_master_id'), table_name='schedulers')
    op.drop_table('schedulers')
    op.drop_index(op.f('ix_masters_archive_organization_id'), table_name='masters_archive')
    op.drop_index(op.f('ix_masters_archive_master_id'), table_name='masters_archive')
    op.drop_table('masters_archive')
    op.drop_index(op.f('ix_templates_organization_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_services_organization_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_organization_archive_organization_id'), table_name='organization_archive')
    op.drop_table('organization_archive')
    op.drop_index(op.f('ix_masters_organization_id'), table_name='masters')
    op.drop_index(op.f('ix_masters_account_id'), table_name='masters')
    op.drop_table('masters')
    op.drop_index(op.f('ix_managers_organization_id'), table_name='managers')
    op.drop_index(op.f('ix_managers_account_id'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_account_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_organizations_is_enable'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_admin_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('accounts')
    # ### end Alembic commands ###
    op.execute("""
    DROP PROCEDURE IF EXISTS constructor.generate_5min_slots_for_master;
    """)
